### ISSUE TITLE
unable to dismiss sticky message

### ISSUE THREAD

**Issue by norcross** [bgardner/bg-mobile-first#1]
currently unable to dismiss the sticky message. on a mobile screen, it could take up a decent amount of real estate. 

a small amount of JS would probably take care of it. I'm willing to write it if you'd like.

**Comment by bgardner** [comment]
How about a display: none in the main css and the a display: block in the desktop media query?

**Comment by norcross** [comment]
well, I'm thinking the message is still valid on mobile, just the ability to dismiss it (or at least hide it) matters. It's probably something that would be useful from a UX perspective regardless of screen size. (this is my opinion, of course)

**Comment by bgardner** [comment]
If you want to whip something up, feel free.  ;-)

**Comment by norcross** [comment]
sounds good. I'll take a spin at it.

**Comment by Marco-G** [comment]
Something quick to fix this.

sticky-message.js
```javascript
jQuery(function( $ ){

	// Add reveal class to sticky message after 100px
	$(document).on("scroll", function(){

		if($(document).scrollTop() > 100){

			$(".sticky-message").addClass("reveal");

		} else {

			$(".sticky-message").removeClass("reveal");

		}

	});

    $(".sticky-message").prepend("<button class='close'>Close</button>");
    $( ".close" ).click(function() {
      $(".sticky-message").hide( "fast");
    });

});
```
style.css
```css

.sticky-message {
	background-color: #333;
	font-size: 16px;
	opacity: 0;
	padding-bottom: 20px;
	padding-top: 20px;
	position: fixed;
	text-align: center;
	width: 100%;
	z-index: 999;
	display: block;
	visibility: hidden;
}

.sticky-message.reveal {
	opacity: 1;
	display: visible;
	visibility: visible;
}
```

**Comment by bgardner** [comment]
One thing to note, the method might change based on something Jen Baumann switched on the Modern Studio theme.  This code:

```
$(".sticky-message").addClass("reveal");

Might become this:

```
$('.sticky-message').fadeIn();

**Comment by Marco-G** [comment]
Might need some testing, I added [jquery.cookie.js](https://github.com/carhartl/jquery-cookie) to prevent the opening of the sticky message on every page. I assume that the sticky message is meant to be shown just once.

functions.php
```php

//* in mobile_first_scripts_styles()

    wp_enqueue_script( 'mobile-first-cookie', get_bloginfo( 'stylesheet_directory' ) . '/js/jquery.cookie.js', array( 'jquery' ), '1.0.0' );
```

sticky-message.js

```javascript
jQuery(function( $ ){
    $(".sticky-message").prepend("<button class='close'>Close</button>");
    // Add reveal class to sticky message after 100px
    $(document).on("scroll", function(){

        if($(document).scrollTop() > 100){
            if (!$.cookie('show_sticky_message')) {
                $(".sticky-message").fadeIn();
            }
        }
    });

    $( ".close" ).on('click',function() {
      $(".sticky-message").fadeOut("normal", function() {
        $(this).remove();
        });
      $.cookie('show_sticky_message', true, { expires: null } ); /*expires closing the browser*/
    });
});
```

style.css
```css
.sticky-message {
    background-color: #333;
    font-size: 16px;
    padding-bottom: 20px;
    padding-top: 20px;
    position: fixed;
    text-align: center;
    width: 100%;
    z-index: 999;
    display: none;
}
```
